package dashboard

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"os/exec"
	"runtime"
	"sort"
	"strings"
	"time"

	"github.com/thesarfo/backtester/backtester"
	"github.com/thesarfo/backtester/binance"
)

type StrategyResult struct {
	Name   string
	Result backtester.Result
}

type Config struct {
	Symbol         string
	Interval       string
	InitialCapital float64
	Candles        []binance.Candle
	Mode           string 
}

type modeLabel struct {
	badge       string 
	baselineSub string 
	footer      string 
	titlePrefix string 
}

func labelsFor(mode string) modeLabel {
	if mode == "stocks" {
		return modeLabel{
			badge:       "Yahoo Finance data",
			baselineSub: "stock raw return",
			footer:      "Generated by Strategy Backtester &bull; Data sourced from Yahoo Finance",
			titlePrefix: "Stocks Backtester",
		}
	}
	return modeLabel{
		badge:       "Binance data",
		baselineSub: "crypto raw return",
		footer:      "Generated by Strategy Backtester &bull; Data sourced from Binance public API",
		titlePrefix: "Crypto Backtester",
	}
}

func Render(results []StrategyResult, cfg Config) error {
	html := buildHTML(results, cfg)

	filename := fmt.Sprintf("backtest_%s_%s.html", cfg.Symbol, time.Now().Format("20060102_150405"))
	if err := os.WriteFile(filename, []byte(html), 0644); err != nil {
		return fmt.Errorf("failed to write dashboard: %w", err)
	}

	fmt.Printf("\nDashboard saved -> %s\n", filename)
	openBrowser(filename)
	return nil
}

func openBrowser(path string) {
	abs, _ := os.Getwd()
	url := "file://" + abs + "/" + path
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "darwin":
		cmd = exec.Command("open", url)
	case "windows":
		cmd = exec.Command("rundll32", "url.dll,FileProtocolHandler", url)
	default:
		cmd = exec.Command("xdg-open", url)
	}
	_ = cmd.Start()
}

func f2(v float64) string { return fmt.Sprintf("%.2f", v) }
func f1(v float64) string { return fmt.Sprintf("%.1f", v) }

func sign(v float64) string {
	if v >= 0 {
		return "+"
	}
	return ""
}

func colorClass(v float64) string {
	if v >= 0 {
		return "green"
	}
	return "red"
}

func best(results []StrategyResult) StrategyResult {
	b := results[0]
	for _, r := range results[1:] {
		if r.Result.TotalReturnPct > b.Result.TotalReturnPct {
			b = r
		}
	}
	return b
}

func bestSharpe(results []StrategyResult) StrategyResult {
	b := results[0]
	for _, r := range results[1:] {
		if r.Result.SharpeRatio > b.Result.SharpeRatio {
			b = r
		}
	}
	return b
}

func lowestDD(results []StrategyResult) StrategyResult {
	b := results[0]
	for _, r := range results[1:] {
		if r.Result.MaxDrawdownPct < b.Result.MaxDrawdownPct {
			b = r
		}
	}
	return b
}

func totalTrades(results []StrategyResult) int {
	n := 0
	for _, r := range results {
		n += r.Result.TotalTrades
	}
	return n
}

func maxReturn(results []StrategyResult) float64 {
	m := 0.0
	for _, r := range results {
		if v := math.Abs(r.Result.TotalReturnPct); v > m {
			m = v
		}
	}
	if m == 0 {
		return 1
	}
	return m
}

func maxDDAll(results []StrategyResult) float64 {
	m := 0.0
	for _, r := range results {
		if r.Result.MaxDrawdownPct > m {
			m = r.Result.MaxDrawdownPct
		}
	}
	if m == 0 {
		return 1
	}
	return m
}

func equityCurveJSON(results []StrategyResult, candles []binance.Candle) string {
	labels := make([]string, len(candles))
	for i, c := range candles {
		if i%50 == 0 {
			labels[i] = c.OpenTime.Format("Jan 02")
		}
	}

	type dataset struct {
		Label       string    `json:"label"`
		Data        []float64 `json:"data"`
		BorderColor string    `json:"borderColor"`
		BorderWidth float64   `json:"borderWidth"`
		PointRadius int       `json:"pointRadius"`
		Tension     float64   `json:"tension"`
		Fill        bool      `json:"fill"`
		BorderDash  []int     `json:"borderDash,omitempty"`
	}

	colors := []string{"#378ADD", "#1D9E75", "#BA7517", "#D4537E", "#888780"}
	var datasets []dataset

	for i, sr := range results {
		color := colors[i%len(colors)]
		d := dataset{
			Label:       sr.Name,
			Data:        sr.Result.EquityCurve,
			BorderColor: color,
			BorderWidth: 2,
			PointRadius: 0,
			Tension:     0.3,
			Fill:        false,
		}
		if strings.Contains(strings.ToLower(sr.Name), "hold") {
			d.BorderDash = []int{5, 4}
			d.BorderWidth = 1.5
			d.BorderColor = "#888780"
		}
		datasets = append(datasets, d)
	}

	out, _ := json.Marshal(map[string]any{
		"labels":   labels,
		"datasets": datasets,
	})
	return string(out)
}

func buildHTML(results []StrategyResult, cfg Config) string {
	lbl := labelsFor(cfg.Mode)

	bst := best(results)
	bsh := bestSharpe(results)
	ldd := lowestDD(results)
	bah := results[len(results)-1]

	dateFrom := cfg.Candles[0].OpenTime.Format("Jan 02 2006")
	dateTo := cfg.Candles[len(cfg.Candles)-1].OpenTime.Format("Jan 02 2006")

	barColors := []string{"#378ADD", "#1D9E75", "#BA7517", "#D4537E", "#888780"}

	sorted := make([]StrategyResult, len(results))
	copy(sorted, results)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Result.TotalReturnPct > sorted[j].Result.TotalReturnPct
	})

	ddSorted := make([]StrategyResult, len(results))
	copy(ddSorted, results)
	sort.Slice(ddSorted, func(i, j int) bool {
		return ddSorted[i].Result.MaxDrawdownPct > ddSorted[j].Result.MaxDrawdownPct
	})

	chartData := equityCurveJSON(results, cfg.Candles)

	var b strings.Builder
	w := func(s string) { b.WriteString(s) }
	wf := func(f string, a ...any) { b.WriteString(fmt.Sprintf(f, a...)) }

	w(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>` + lbl.titlePrefix + ` - ` + cfg.Symbol + `</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.js"></script>
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#f5f5f4;color:#1a202c;font-size:14px}
.header{background:#fff;border-bottom:1px solid #e2e8f0;padding:14px 24px;display:flex;align-items:center;justify-content:space-between}
.header-left h1{font-size:16px;font-weight:600;color:#1a202c}
.header-left p{font-size:12px;color:#718096;margin-top:2px}
.badge{font-size:11px;padding:3px 10px;border-radius:99px;font-weight:500;background:#ebf5fb;color:#1a5276}
.badge.stocks{background:#eaf3de;color:#276749}
.dash{padding:20px 24px;max-width:1300px;margin:0 auto}
.metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;margin-bottom:18px}
.metric-card{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:14px 16px}
.metric-label{font-size:11px;color:#718096;text-transform:uppercase;letter-spacing:.04em;margin-bottom:5px}
.metric-value{font-size:20px;font-weight:600;color:#1a202c;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.metric-sub{font-size:12px;margin-top:4px}
.metric-sub.green{color:#276749}
.metric-sub.red{color:#9b2c2c}
.metric-sub.muted{color:#718096}
.card{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:16px 20px}
.card-title{font-size:13px;font-weight:600;color:#1a202c;margin-bottom:14px}
.equity-wrap{margin-bottom:18px}
.chart-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px;flex-wrap:wrap;gap:8px}
.legend{display:flex;flex-wrap:wrap;gap:12px}
.legend-item{display:flex;align-items:center;gap:5px;font-size:12px;color:#4a5568}
.legend-dot{width:10px;height:10px;border-radius:2px;flex-shrink:0}
.bottom-grid{display:grid;grid-template-columns:3fr 2fr;gap:16px;margin-bottom:18px}
table{width:100%;border-collapse:collapse}
th{font-size:11px;color:#718096;text-align:left;padding:0 12px 8px 0;border-bottom:1px solid #e2e8f0;font-weight:500;white-space:nowrap}
td{padding:9px 12px 9px 0;border-bottom:1px solid #f0f0ef;color:#1a202c;white-space:nowrap}
tr:last-child td{border-bottom:none}
td:not(:first-child),th:not(:first-child){text-align:right}
.green{color:#276749;font-weight:500}
.red{color:#9b2c2c;font-weight:500}
.bar-section{display:flex;flex-direction:column;gap:18px}
.bar-section-title{font-size:11px;color:#718096;text-transform:uppercase;letter-spacing:.04em;margin-bottom:8px}
.bar-wrap{display:flex;flex-direction:column;gap:8px}
.bar-row{display:flex;align-items:center;gap:10px}
.bar-label{font-size:12px;color:#4a5568;width:130px;flex-shrink:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.bar-track{flex:1;height:9px;background:#f0f0ef;border-radius:99px;overflow:hidden}
.bar-fill{height:100%;border-radius:99px}
.bar-val{font-size:12px;font-weight:500;width:52px;text-align:right;flex-shrink:0}
.trade-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}
.footer{text-align:center;font-size:11px;color:#a0aec0;padding:20px 0 32px}
</style>
</head>
<body>
`)

	badgeClass := "badge"
	if cfg.Mode == "stocks" {
		badgeClass = "badge stocks"
	}
	w(`<div class="header"><div class="header-left">`)
	w(`<h1>` + lbl.titlePrefix + ` &mdash; ` + cfg.Symbol + `</h1>`)
	w(`<p>` + cfg.Interval + ` &nbsp;&bull;&nbsp; `)
	wf("%d", len(cfg.Candles))
	w(` candles &nbsp;&bull;&nbsp; ` + dateFrom + ` to ` + dateTo + ` &nbsp;&bull;&nbsp; Starting capital: $`)
	wf("%.0f", cfg.InitialCapital)
	w(`</p></div>`)
	w(`<span class="` + badgeClass + `">` + lbl.badge + `</span>`)
	w(`</div>`)

	w(`<div class="dash">`)

	w(`<div class="metrics">`)
	type metricDef struct{ label, value, sub, cls string }
	for _, m := range []metricDef{
		{
			"Best strategy",
			bst.Name,
			sign(bst.Result.TotalReturnPct) + f2(bst.Result.TotalReturnPct) + "% return",
			colorClass(bst.Result.TotalReturnPct),
		},
		{
			"Buy &amp; hold baseline",
			sign(bah.Result.TotalReturnPct) + f2(bah.Result.TotalReturnPct) + "%",
			lbl.baselineSub, // ← "crypto raw return" or "stock raw return"
			"muted",
		},
		{
			"Best Sharpe ratio",
			f2(bsh.Result.SharpeRatio),
			bsh.Name,
			"muted",
		},
		{
			"Lowest drawdown",
			"-" + f2(ldd.Result.MaxDrawdownPct) + "%",
			ldd.Name,
			"red",
		},
		{
			"Total trades run",
			fmt.Sprintf("%d", totalTrades(results)),
			"across all strategies",
			"muted",
		},
	} {
		w(`<div class="metric-card">`)
		w(`<div class="metric-label">` + m.label + `</div>`)
		w(`<div class="metric-value">` + m.value + `</div>`)
		w(`<div class="metric-sub ` + m.cls + `">` + m.sub + `</div>`)
		w(`</div>`)
	}
	w(`</div>`)

	w(`<div class="card equity-wrap"><div class="chart-header">`)
	w(`<span class="card-title">Equity curves</span>`)
	w(`<div class="legend">`)
	for i, sr := range results {
		color := barColors[i%len(barColors)]
		if strings.Contains(strings.ToLower(sr.Name), "hold") {
			color = "#888780"
		}
		w(`<span class="legend-item"><span class="legend-dot" style="background:` + color + `"></span>` + sr.Name + `</span>`)
	}
	w(`</div></div>`)
	w(`<div style="position:relative;width:100%;height:280px;"><canvas id="equityChart"></canvas></div>`)
	w(`</div>`)

	w(`<div class="bottom-grid">`)

	w(`<div class="card"><div class="card-title">Strategy comparison</div><table>`)
	w(`<tr><th>Strategy</th><th>Return</th><th>Max DD</th><th>Sharpe</th><th>Win rate</th><th>Profit factor</th></tr>`)
	for _, sr := range sorted {
		r := sr.Result
		pf := "&infin;"
		if !math.IsInf(r.ProfitFactor, 1) {
			pf = f2(r.ProfitFactor)
		}
		w(`<tr>`)
		w(`<td>` + sr.Name + `</td>`)
		w(`<td class="` + colorClass(r.TotalReturnPct) + `">` + sign(r.TotalReturnPct) + f2(r.TotalReturnPct) + `%</td>`)
		w(`<td class="red">-` + f2(r.MaxDrawdownPct) + `%</td>`)
		w(`<td>` + f2(r.SharpeRatio) + `</td>`)
		w(`<td>` + f1(r.WinRate) + `%</td>`)
		w(`<td>` + pf + `</td>`)
		w(`</tr>`)
	}
	w(`</table></div>`)

	// Bar chart panel
	w(`<div class="card"><div class="card-title">Return vs. drawdown</div><div class="bar-section">`)

	w(`<div><div class="bar-section-title">Return</div><div class="bar-wrap">`)
	maxR := maxReturn(results)
	for i, sr := range sorted {
		pct := math.Abs(sr.Result.TotalReturnPct) / maxR * 100
		color := barColors[i%len(barColors)]
		w(`<div class="bar-row">`)
		w(`<div class="bar-label">` + sr.Name + `</div>`)
		wf(`<div class="bar-track"><div class="bar-fill" style="width:%.1f%%;background:`+color+`"></div></div>`, pct)
		w(`<div class="bar-val ` + colorClass(sr.Result.TotalReturnPct) + `">` + sign(sr.Result.TotalReturnPct) + f2(sr.Result.TotalReturnPct) + `%</div>`)
		w(`</div>`)
	}
	w(`</div></div>`)

	w(`<div><div class="bar-section-title">Max drawdown (lower is better)</div><div class="bar-wrap">`)
	maxD := maxDDAll(results)
	for _, sr := range ddSorted {
		pct := sr.Result.MaxDrawdownPct / maxD * 100
		w(`<div class="bar-row">`)
		w(`<div class="bar-label">` + sr.Name + `</div>`)
		wf(`<div class="bar-track"><div class="bar-fill" style="width:%.1f%%;background:#E24B4A"></div></div>`, pct)
		w(`<div class="bar-val red">-` + f2(sr.Result.MaxDrawdownPct) + `%</div>`)
		w(`</div>`)
	}
	w(`</div></div>`)
	w(`</div></div>`) 
	w(`</div>`)       

	w(`<div class="trade-grid">`)

	w(`<div class="card"><div class="card-title">Recent trades &mdash; ` + bst.Name + ` (last 20)</div>`)
	w(`<table><tr><th>#</th><th>Entry</th><th>Exit</th><th>P&amp;L ($)</th><th>P&amp;L (%)</th></tr>`)
	trades := bst.Result.Trades
	tstart := 0
	if len(trades) > 20 {
		tstart = len(trades) - 20
	}
	for idx, t := range trades[tstart:] {
		num := tstart + idx + 1
		pnlSign := "+"
		if t.PnL < 0 {
			pnlSign = "-"
		}
		w(`<tr>`)
		wf(`<td>#%d</td>`, num)
		w(`<td>$` + f2(t.EntryPrice) + `</td>`)
		w(`<td>$` + f2(t.ExitPrice) + `</td>`)
		w(`<td class="` + colorClass(t.PnL) + `">` + pnlSign + `$` + f2(math.Abs(t.PnL)) + `</td>`)
		w(`<td class="` + colorClass(t.PnLPct) + `">` + sign(t.PnLPct) + f2(t.PnLPct) + `%</td>`)
		w(`</tr>`)
	}
	w(`</table></div>`)

	dataSource := "Binance public API"
	if cfg.Mode == "stocks" {
		dataSource = "Yahoo Finance"
	}
	w(`<div class="card"><div class="card-title">Run summary</div><table>`)
	for _, row := range []struct{ label, value string }{
		{"Market", strings.Title(cfg.Mode)},
		{"Symbol", cfg.Symbol},
		{"Interval", cfg.Interval},
		{"Period", dateFrom + " to " + dateTo},
		{"Candles", fmt.Sprintf("%d", len(cfg.Candles))},
		{"Starting capital", fmt.Sprintf("$%.2f", cfg.InitialCapital)},
		{"Commission per trade", "0.10%"},
		{"Data source", dataSource},
		{"Strategies tested", fmt.Sprintf("%d", len(results))},
		{"Generated", time.Now().Format("Jan 02 2006, 15:04")},
	} {
		w(`<tr><td style="color:#718096;">` + row.label + `</td><td style="text-align:right;">` + row.value + `</td></tr>`)
	}
	w(`</table></div>`)
	w(`</div>`) 

	w(`</div>`) 
	w(`<div class="footer">` + lbl.footer + `</div>`)

	w(`<script>
var chartData = `)
	w(chartData)
	w(`;
new Chart(document.getElementById('equityChart'), {
  type: 'line',
  data: chartData,
  options: {
    responsive: true,
    maintainAspectRatio: false,
    interaction: { mode: 'index', intersect: false },
    plugins: {
      legend: { display: false },
      tooltip: {
        callbacks: {
          label: function(ctx) {
            return ' ' + ctx.dataset.label + ': $' + ctx.parsed.y.toLocaleString(undefined, { maximumFractionDigits: 0 });
          }
        }
      }
    },
    scales: {
      x: {
        grid: { display: false },
        ticks: {
          color: '#a0aec0', font: { size: 11 }, maxRotation: 0,
          callback: function(val) { return this.getLabelForValue(val) || ''; }
        }
      },
      y: {
        grid: { color: 'rgba(0,0,0,0.05)' },
        ticks: {
          color: '#a0aec0', font: { size: 11 },
          callback: function(v) { return '$' + (v >= 1000 ? (v/1000).toFixed(1) + 'k' : v.toFixed(0)); }
        }
      }
    }
  }
});
</script>
</body>
</html>`)

	return b.String()
}
